#created on: Oct 31, 2011
package ec.gob.gim.rules.pf2011
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.common.model.FiscalPeriod;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.common.model.LegalEntity;
import java.math.BigDecimal;
import java.util.Calendar;
import ec.gob.gim.revenue.model.adjunct.BusinessLocalReference;

#list any import classes here.

rule "Descuento Perdida ejercicio fiscal"
	no-loop true
	salience 0
	when		
		$itemPatente : Item(entry.name == "DESCUENTO PERDIDA EJERCICIO FISCAL");
		$mb : MunicipalBond();
		$ad : BusinessLocalReference();
		eval($ad.getLostFiscalYear()==true);
	then		
		$itemPatente.setTotal($mb.getItems().get(0).getTotal().multiply(new BigDecimal(0.5)));			
end
