#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.waterservice

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;

dialect "java"


rule "Plan Maestro"
	no-loop true
	salience 0
	when
		$item : Item(entry.code == "00460");
		$mb : MunicipalBond(items contains $item);
	then
		Item $itemBase = $mb.getItems().get(0);		
		$item.setValue($itemBase.getValue().multiply(new BigDecimal(0.20)));
		$item.setTotal($item.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));
end
