#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.waterservice

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.cadaster.model.Property;
import ec.gob.gim.cadaster.model.Domain;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;
import ec.gob.gim.waterservice.model.Consumption;
import ec.gob.gim.waterservice.model.WaterSupply;
import ec.gob.gim.waterservice.model.WaterSupplyCategory;
import ec.gob.gim.revenue.model.adjunct.WaterServiceReference;

dialect "java"

rule "Seguridad Ciudadana"
	no-loop true
	salience 5
	when
		$item : Item(entry.code == "00464");
		$mb : MunicipalBond(items contains $item);
		$wsr : WaterServiceReference();
	then		
		$item.setValue($wsr.getConsumption().getAmount().multiply(new BigDecimal(0.02)));
		$item.setTotal($item.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));		
end
