#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.waterservice

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.cadaster.model.Property;
import ec.gob.gim.cadaster.model.Domain;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;
import ec.gob.gim.waterservice.model.Consumption;
import ec.gob.gim.waterservice.model.WaterSupply;
import ec.gob.gim.waterservice.model.WaterSupplyCategory;
import ec.gob.gim.revenue.model.adjunct.WaterServiceReference;

dialect "java"

rule "Impuesto agua 00076"
	no-loop true
	salience 1
	when
		$itemBase : Item(entry.code == "00076");
		$mb : MunicipalBond(items contains $itemBase);
		$wsr : WaterServiceReference();
	then
		aguaPotable($wsr.getConsumption(), $itemBase, $wsr);
		
end


function void aguaPotable(Consumption $comp, Item $itemBase, WaterServiceReference $wsr){	
	BigDecimal $factorSubstract = BigDecimal.ZERO;
	BigDecimal $factorMultiply = BigDecimal.ZERO;
	if($comp.getWaterSupply().getWaterSupplyCategory().getName().equals("RESIDENCIAL")){
			
		if($comp.getAmount().doubleValue() >= 0 && $comp.getAmount().doubleValue() <=10){
			$itemBase.setValue(new BigDecimal(1.516));			
		}
		
		if($comp.getAmount().doubleValue() >= 11 && $comp.getAmount().doubleValue() <=20){
			$itemBase.setValue(new BigDecimal(2.330));
			$factorSubstract = new BigDecimal(11);
			$factorMultiply = new BigDecimal(0.090);
		}
		
		if($comp.getAmount().doubleValue() >= 21 && $comp.getAmount().doubleValue() <=50){
			$itemBase.setValue(new BigDecimal(3.338));
			$factorSubstract = new BigDecimal(21);
			$factorMultiply = new BigDecimal(0.166);			
		}
		
		if($comp.getAmount().doubleValue() >= 51 && $comp.getAmount().doubleValue() <=70){
			$itemBase.setValue(new BigDecimal(10.481));
			$factorSubstract = new BigDecimal(51);
			$factorMultiply = new BigDecimal(0.204);			
		}
		
		if($comp.getAmount().doubleValue() >= 71 && $comp.getAmount().doubleValue() <=90){
			$itemBase.setValue(new BigDecimal(18.310));
			$factorSubstract = new BigDecimal(71);
			$factorMultiply = new BigDecimal(0.237);			
		}
		
		if($comp.getAmount().doubleValue() >= 91 && $comp.getAmount().doubleValue() <=100){
			$itemBase.setValue(new BigDecimal(23.729));
			$factorSubstract = new BigDecimal(91);
			$factorMultiply = new BigDecimal(0.328);
		}
		
		if($comp.getAmount().doubleValue() >= 101){
			$itemBase.setValue(new BigDecimal(28.902));
			$factorSubstract = new BigDecimal(101);
			$factorMultiply = new BigDecimal(0.390);	
		}		
				
	}
	
	if($comp.getWaterSupply().getWaterSupplyCategory().getName().equals("COMERCIAL")){
			
		if($comp.getAmount().doubleValue() >= 0 && $comp.getAmount().doubleValue() <=10){
			$itemBase.setValue(new BigDecimal(6.493));
		}
		
		if($comp.getAmount().doubleValue() >= 11 && $comp.getAmount().doubleValue() <=20){
			$itemBase.setValue(new BigDecimal(6.493));
			$factorSubstract = new BigDecimal(10);
			$factorMultiply = new BigDecimal(0.328);
		}
		
		if($comp.getAmount().doubleValue() >= 21 && $comp.getAmount().doubleValue() <=50){
			$itemBase.setValue(new BigDecimal(9.773));
			$factorSubstract = new BigDecimal(20);
			$factorMultiply = new BigDecimal(0.518);
		}
		
		if($comp.getAmount().doubleValue() >= 51 && $comp.getAmount().doubleValue() <=100){
			$itemBase.setValue(new BigDecimal(25.313));
			$factorSubstract = new BigDecimal(50);
			$factorMultiply = new BigDecimal(0.645);
		}
		
		if($comp.getAmount().doubleValue() >= 101){
			$itemBase.setValue(new BigDecimal(57.563));
			$factorSubstract = new BigDecimal(100);
			$factorMultiply = new BigDecimal(0.973);
		}	
				
	}
	
	if($comp.getWaterSupply().getWaterSupplyCategory().getName().equals("INDUSTRIAL")){
			
		if($comp.getAmount().doubleValue() >= 0 && $comp.getAmount().doubleValue() <=10){
			$itemBase.setValue(new BigDecimal(9.495));
		}
		
		if($comp.getAmount().doubleValue() >= 11 && $comp.getAmount().doubleValue() <=20){
			$itemBase.setValue(new BigDecimal(9.495));
			$factorSubstract = new BigDecimal(10);
			$factorMultiply = new BigDecimal(0.487);
		}
		
		if($comp.getAmount().doubleValue() >= 21 && $comp.getAmount().doubleValue() <=50){
			$itemBase.setValue(new BigDecimal(14.365));
			$factorSubstract = new BigDecimal(20);
			$factorMultiply = new BigDecimal(0.783);
		}
		
		if($comp.getAmount().doubleValue() >= 51 && $comp.getAmount().doubleValue() <=100){
			$itemBase.setValue(new BigDecimal(37.855));
			$factorSubstract = new BigDecimal(50);
			$factorMultiply = new BigDecimal(0.973);
		}
		
		if($comp.getAmount().doubleValue() >= 101){
			$itemBase.setValue(new BigDecimal(86.505));
			$factorSubstract = new BigDecimal(100);
			$factorMultiply = new BigDecimal(1.463);
		}	
				
	}
	
	if($comp.getWaterSupply().getWaterSupplyCategory().getName().equals("OFICIAL")){
			
		if($comp.getAmount().doubleValue() >= 0 && $comp.getAmount().doubleValue() <=10){
			$itemBase.setValue(new BigDecimal(3.010));
		}
		
		if($comp.getAmount().doubleValue() >= 11 && $comp.getAmount().doubleValue() <=20){
			$itemBase.setValue(new BigDecimal(3.010));
			$factorSubstract = new BigDecimal(10);
			$factorMultiply = new BigDecimal(0.329);
		}
		
		if($comp.getAmount().doubleValue() >= 21 && $comp.getAmount().doubleValue() <=50){
			$itemBase.setValue(new BigDecimal(6.300));
			$factorSubstract = new BigDecimal(20);
			$factorMultiply = new BigDecimal(0.340);
		}
		
		if($comp.getAmount().doubleValue() >= 51 && $comp.getAmount().doubleValue() <=100){
			$itemBase.setValue(new BigDecimal(16.500));
			$factorSubstract = new BigDecimal(30);
			$factorMultiply = new BigDecimal(0.397);
		}
		
		if($comp.getAmount().doubleValue() >= 101){
			$itemBase.setValue(new BigDecimal(36.35));
			$factorSubstract = new BigDecimal(100);
			$factorMultiply = new BigDecimal(0.448);
		}	
				
	}
	
	if($comp.getWaterSupply().getWaterSupplyCategory().getName().equals("OFICIAL MEDIO")){
			
		if($comp.getAmount().doubleValue() >= 0 && $comp.getAmount().doubleValue() <=10){
			$itemBase.setValue(new BigDecimal(1.516));
		}
		
		if($comp.getAmount().doubleValue() >= 11 && $comp.getAmount().doubleValue() <=20){
			$itemBase.setValue(new BigDecimal(1.516));
			$factorSubstract = new BigDecimal(10);
			$factorMultiply = new BigDecimal(0.164);
		}
		
		if($comp.getAmount().doubleValue() >= 21 && $comp.getAmount().doubleValue() <=50){
			$itemBase.setValue(new BigDecimal(3.156));
			$factorSubstract = new BigDecimal(20);
			$factorMultiply = new BigDecimal(0.173);
		}
		
		if($comp.getAmount().doubleValue() >= 51 && $comp.getAmount().doubleValue() <=100){
			$itemBase.setValue(new BigDecimal(8.346));
			$factorSubstract = new BigDecimal(50);
			$factorMultiply = new BigDecimal(0.200);
		}
		
		if($comp.getAmount().doubleValue() >= 101){
			$itemBase.setValue(new BigDecimal(18.346));
			$factorSubstract = new BigDecimal(100);
			$factorMultiply = new BigDecimal(0.223);
		}	
				
	}
	
	if($comp.getWaterSupply().getWaterSupplyCategory().getName().equals("TERCERA EDAD")){
			
		if($comp.getAmount().doubleValue() >= 0 && $comp.getAmount().doubleValue() <=10){
			$itemBase.setValue(new BigDecimal(0.760));
		}
		
		if($comp.getAmount().doubleValue() >= 11 && $comp.getAmount().doubleValue() <=20){
			$itemBase.setValue(new BigDecimal(1.165));
			$factorSubstract = new BigDecimal(11);
			$factorMultiply = new BigDecimal(0.045);
		}
		
		if($comp.getAmount().doubleValue() >= 21 && $comp.getAmount().doubleValue() <=30){
			$itemBase.setValue(new BigDecimal(1.768));
			$factorSubstract = new BigDecimal(21);
			$factorMultiply = new BigDecimal(0.166);
		}
		
		if($comp.getAmount().doubleValue() >= 31 && $comp.getAmount().doubleValue() <=50){
			$itemBase.setValue(new BigDecimal(4.260));
			$factorSubstract = new BigDecimal(31);
			$factorMultiply = new BigDecimal(0.166);
		}
		
		if($comp.getAmount().doubleValue() >= 51 && $comp.getAmount().doubleValue() <=70){
			$itemBase.setValue(new BigDecimal(9.184));
			$factorSubstract = new BigDecimal(51);
			$factorMultiply = new BigDecimal(0.204);
		}
		
		if($comp.getAmount().doubleValue() >= 71 && $comp.getAmount().doubleValue() <=90){
			$itemBase.setValue(new BigDecimal(16.738));
			$factorSubstract = new BigDecimal(71);
			$factorMultiply = new BigDecimal(0.237);
		}
		
		if($comp.getAmount().doubleValue() >= 91 && $comp.getAmount().doubleValue() <=100){
			$itemBase.setValue(new BigDecimal(21.876));
			$factorSubstract = new BigDecimal(91);
			$factorMultiply = new BigDecimal(0.328);
		}
		
		if($comp.getAmount().doubleValue() >= 101){
			$itemBase.setValue(new BigDecimal(27.328));
			$factorSubstract = new BigDecimal(101);
			$factorMultiply = new BigDecimal(0.390);
		}	
				
	}
	
	if($comp.getWaterSupply().getWaterSupplyCategory().getName().equals("ESPECIAL")){
			
		if($comp.getAmount().doubleValue() >= 0 && $comp.getAmount().doubleValue() <=10){
			$itemBase.setValue(new BigDecimal(0.760));
		}
		
		if($comp.getAmount().doubleValue() >= 11 && $comp.getAmount().doubleValue() <=20){
			$itemBase.setValue(new BigDecimal(1.165));
			$factorSubstract = new BigDecimal(11);
			$factorMultiply = new BigDecimal(0.045);
		}
		
		if($comp.getAmount().doubleValue() >= 21 && $comp.getAmount().doubleValue() <=30){
			$itemBase.setValue(new BigDecimal(1.768));
			$factorSubstract = new BigDecimal(21);
			$factorMultiply = new BigDecimal(0.166);
		}
		
		if($comp.getAmount().doubleValue() >= 31 && $comp.getAmount().doubleValue() <=50){
			$itemBase.setValue(new BigDecimal(4.260));
			$factorSubstract = new BigDecimal(31);
			$factorMultiply = new BigDecimal(0.166);
		}
		
		if($comp.getAmount().doubleValue() >= 51 && $comp.getAmount().doubleValue() <=70){
			$itemBase.setValue(new BigDecimal(9.184));
			$factorSubstract = new BigDecimal(51);
			$factorMultiply = new BigDecimal(0.204);
		}
		
		if($comp.getAmount().doubleValue() >= 71 && $comp.getAmount().doubleValue() <=90){
			$itemBase.setValue(new BigDecimal(16.738));
			$factorSubstract = new BigDecimal(71);
			$factorMultiply = new BigDecimal(0.237);
		}
		
		if($comp.getAmount().doubleValue() >= 91 && $comp.getAmount().doubleValue() <=100){
			$itemBase.setValue(new BigDecimal(21.876));
			$factorSubstract = new BigDecimal(91);
			$factorMultiply = new BigDecimal(0.328);
		}
		
		if($comp.getAmount().doubleValue() >= 101){
			$itemBase.setValue(new BigDecimal(27.328));
			$factorSubstract = new BigDecimal(101);
			$factorMultiply = new BigDecimal(0.390);
		}			
	}

	BigDecimal $exemptionValue = BigDecimal.ZERO;
	
	$itemBase.setValue($itemBase.getValue().add($comp.getAmount().subtract($factorSubstract).multiply($factorMultiply)));	
	
	# tercera edad
	if($comp.getWaterSupply().getApplyElderlyExemption() && $comp.getWaterSupply().getWaterSupplyCategory().getName().equals("RESIDENCIAL")){
		#
		if($comp.getAmount().doubleValue() <= 20){
			$exemptionValue	= $itemBase.getValue().divide(new BigDecimal(2)).setScale(2,BigDecimal.ROUND_HALF_UP);
		}
		if($comp.getAmount().doubleValue() > 20){
			$exemptionValue = new BigDecimal(1.557).setScale(2,BigDecimal.ROUND_HALF_UP);
		}
	}
	if($comp.getWaterSupply().getApplyElderlyExemption() && $comp.getWaterSupply().getWaterSupplyCategory().getName().equals("COMERCIAL")){
		if($comp.getAmount().doubleValue() <= 20){
			$exemptionValue = $itemBase.getValue().divide(new BigDecimal(2)).setScale(2,BigDecimal.ROUND_HALF_UP);
		}
		if($comp.getAmount().doubleValue() > 20){
			$exemptionValue = new BigDecimal(4.887).setScale(2,BigDecimal.ROUND_HALF_UP);
		}
	}
	# discapacitados la mitad de 10m3 consumidos
	if($comp.getWaterSupply().getApplySpecialExemption() && $comp.getWaterSupply().getWaterSupplyCategory().getName().equals("RESIDENCIAL")){
		$exemptionValue = new BigDecimal(0.758).setScale(2,BigDecimal.ROUND_HALF_UP);
	}
	if($comp.getWaterSupply().getApplySpecialExemption() && $comp.getWaterSupply().getWaterSupplyCategory().getName().equals("COMERCIAL")){
		$exemptionValue = new BigDecimal(3.247).setScale(2,BigDecimal.ROUND_HALF_UP);
	}
	
	$comp.setExemptionValue($exemptionValue);
	$wsr.setExemptionValue($exemptionValue);
	$itemBase.setTotal($itemBase.getValue().subtract($exemptionValue).setScale(2,BigDecimal.ROUND_HALF_UP));
	
}