
package ec.gob.loja.middleapp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ec.gob.ant.EntradaPersona;
import ec.gob.ant.EntradaReplicacion;
import ec.gob.ant.Infraccion;
import ec.gob.ant.Persona;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InfractionWSV2", targetNamespace = "http://middleapp.loja.gob.ec/")
@XmlSeeAlso({
    ec.gob.loja.middleapp.ObjectFactory.class,
    ec.gob.ant.ObjectFactory.class
})
public interface InfractionWSV2 {


    /**
     * 
     * @param placa
     * @return
     *     returns ec.gob.loja.middleapp.ResponseVehiculo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarVehiculo", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarVehiculo")
    @ResponseWrapper(localName = "consultarVehiculoResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarVehiculoResponse")
    public ResponseVehiculo consultarVehiculo(
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @param imagen
     * @param tipo
     * @param idInfraccion
     * @return
     *     returns ec.gob.loja.middleapp.ResponseResultado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresarImagen", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.IngresarImagen")
    @ResponseWrapper(localName = "ingresarImagenResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.IngresarImagenResponse")
    public ResponseResultado ingresarImagen(
        @WebParam(name = "tipo", targetNamespace = "")
        String tipo,
        @WebParam(name = "imagen", targetNamespace = "")
        byte[] imagen,
        @WebParam(name = "idInfraccion", targetNamespace = "")
        String idInfraccion);

    /**
     * 
     * @param infraccion
     * @return
     *     returns ec.gob.loja.middleapp.ResponseDatosSalidaInfracciones
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "replicarInfraccion", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ReplicarInfraccion")
    @ResponseWrapper(localName = "replicarInfraccionResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ReplicarInfraccionResponse")
    public ResponseDatosSalidaInfracciones replicarInfraccion(
        @WebParam(name = "infraccion", targetNamespace = "")
        EntradaReplicacion infraccion);

    /**
     * 
     * @param identificacion
     * @param tipoIdentificacion
     * @param idEmpresa
     * @param placa
     * @return
     *     returns ec.gob.loja.middleapp.ResponseDeuda
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeudas", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarDeudas")
    @ResponseWrapper(localName = "consultarDeudasResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarDeudasResponse")
    public ResponseDeuda consultarDeudas(
        @WebParam(name = "tipoIdentificacion", targetNamespace = "")
        String tipoIdentificacion,
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "idEmpresa", targetNamespace = "")
        String idEmpresa);

    /**
     * 
     * @param idInfraccion
     * @return
     *     returns ec.gob.loja.middleapp.ResponseInfraccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarInfraccion", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarInfraccion")
    @ResponseWrapper(localName = "consultarInfraccionResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarInfraccionResponse")
    public ResponseInfraccion consultarInfraccion(
        @WebParam(name = "idInfraccion", targetNamespace = "")
        String idInfraccion);

    /**
     * 
     * @param placa
     * @return
     *     returns ec.gob.loja.middleapp.ResponseBloqueos
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarBloqueos", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarBloqueos")
    @ResponseWrapper(localName = "consultarBloqueosResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarBloqueosResponse")
    public ResponseBloqueos consultarBloqueos(
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @param datos
     * @return
     *     returns ec.gob.loja.middleapp.ResponseDatosLicencia
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarLicencia", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarLicencia")
    @ResponseWrapper(localName = "consultarLicenciaResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarLicenciaResponse")
    public ResponseDatosLicencia consultarLicencia(
        @WebParam(name = "datos", targetNamespace = "")
        EntradaPersona datos);

    /**
     * 
     * @param infraccion
     * @return
     *     returns ec.gob.loja.middleapp.ResponseDatosSalidaInfracciones
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ingresarInfraccion", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.IngresarInfraccion")
    @ResponseWrapper(localName = "ingresarInfraccionResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.IngresarInfraccionResponse")
    public ResponseDatosSalidaInfracciones ingresarInfraccion(
        @WebParam(name = "infraccion", targetNamespace = "")
        Infraccion infraccion);

    /**
     * 
     * @param idPersona
     * @return
     *     returns ec.gob.loja.middleapp.ResponseFoto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarFoto", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarFoto")
    @ResponseWrapper(localName = "consultarFotoResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarFotoResponse")
    public ResponseFoto consultarFoto(
        @WebParam(name = "idPersona", targetNamespace = "")
        String idPersona);

    /**
     * 
     * @param placa
     * @return
     *     returns ec.gob.loja.middleapp.ResponseHistorialDominio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarHistorial", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarHistorial")
    @ResponseWrapper(localName = "consultarHistorialResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarHistorialResponse")
    public ResponseHistorialDominio consultarHistorial(
        @WebParam(name = "placa", targetNamespace = "")
        String placa);

    /**
     * 
     * @param persona
     * @return
     *     returns ec.gob.loja.middleapp.ResponseDeclaracion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarDeclaracionJur", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarDeclaracionJur")
    @ResponseWrapper(localName = "consultarDeclaracionJurResponse", targetNamespace = "http://middleapp.loja.gob.ec/", className = "ec.gob.loja.middleapp.ConsultarDeclaracionJurResponse")
    public ResponseDeclaracion consultarDeclaracionJur(
        @WebParam(name = "persona", targetNamespace = "")
        Persona persona);

}
