INSERT INTO role (id, description, name) VALUES (1, 'Administrador general', 'ROOT');
INSERT INTO role (id, description, name) VALUES (2, 'Cajero del Sistema', 'CAJERO SYSTEM');
INSERT INTO role (id, description, name) VALUES (3, 'Emisor del Sistema', 'EMISOR SYSTEM');
INSERT INTO role (id, description, name) VALUES (4, 'Cajero compensaciones del Sistema', 'CAJERO COMPENSACIONES SYSTEM');
INSERT INTO role (id, description, name) VALUES (5, 'Jefe rentas del Sistema', 'JEFE RENTAS SYSTEM');
INSERT INTO role (id, description, name) VALUES (6, 'Jefe recaudaciones del Sistema', 'JEFE RECAUDACIONES SYSTEM');
INSERT INTO role (id, description, name) VALUES (7, 'PreEmisor del Sistema', 'PREEMISOR SYSTEM');
INSERT INTO role (id, description, name) VALUES (8, 'Información del Sistema', 'INFORMACION');
INSERT INTO role (id, description, name) VALUES (9, 'Secretaria de Recaudaciones', 'SECRETARIA RECAUDACIONES');
INSERT INTO role (id, description, name) VALUES (10, 'Acciones de Usuario para Cajero', 'CAJERO');
INSERT INTO role (id, description, name) VALUES (11, 'Digitación de Fichas Catastrales', 'DIGITADOR CATASTRO');
INSERT INTO role (id, description, name) VALUES (12, 'Inicial para todos', 'GENERAL');
INSERT INTO role (id, description, name) VALUES (13, 'Acciones para el Rol Emisor de Rentas', 'EMISOR');
INSERT INTO role (id, description, name) VALUES (14, 'Acciones para el Rol Emisor de Jefatura de Rentas', 'JEFE RENTAS');
INSERT INTO role (id, description, name) VALUES (15, 'Acciones para el Rol de Jefatura de Recaudaciones', 'JEFE RECAUDACIONES');
INSERT INTO role (id, description, name) VALUES (16, 'Acciones para el Rol de Dirección de Avalúos y Catastros', 'JEFE AVALUOS Y CATASTROS');
INSERT INTO role (id, description, name) VALUES (17, 'Acciones para el Rol de Lider de Actualización Catastral', 'JEFE ACTUALIZACION CATASTROS');
INSERT INTO role (id, description, name) VALUES (18, 'Acciones para el Rol de Jefatura de Comercialización de Agua Potable', 'JEFE COMERCIALIZACION');
INSERT INTO role (id, description, name) VALUES (19, 'Acciones para el Rol de Digitador de Lecturas de Agua Potable', 'DIGITADOR LECTURAS AP');
INSERT INTO role (id, description, name) VALUES (20, 'Acciones para el Rol de Digitador de Presupuestos para Agua Potable', 'DIGITADOR PRESUPUESTOS AP');
INSERT INTO role (id, description, name) VALUES (21, 'Usuarios para emitir multas del SIMERT', 'SIMERT');
INSERT INTO role (id, description, name) VALUES (22, 'Rol para realizar pago por compensaciones en el sector publico y privado, además permite editar usuarios.', 'CAJERO COMPENSACIONES');
INSERT INTO role (id, description, name) VALUES (23, 'PERMISO PARA IMPRIMIR CERTIFICADOS DE SOLVENCIA', 'CERTIFICADOS DE SOLVENCIA');
INSERT INTO role (id, description, name) VALUES (24, 'PERMISOS PARA ADMINISTRAR LOCALES COMERCIALES', 'CATASTRO COMERCIAL');
INSERT INTO role (id, description, name) VALUES (25, 'Administración de contribuyentes para crear, editar y actualizar', 'ADMINISTRACION CONTRIBUYENTES');
INSERT INTO role (id, description, name) VALUES (26, 'Acciones para el jefe de coactivas', 'COACTIVAS ');
INSERT INTO role (id, description, name) VALUES (27, 'Permite ver el detalle de los titulos en el estado de cuenta', 'VISUALIZAR DETALLE DE TITULOS SYSTEM');
INSERT INTO role (id, description, name) VALUES (28, 'Transacciones de Agua Potable', 'TRANSACCIONES AGUA POTABLE');
INSERT INTO role (id, description, name) VALUES (29, 'Revisor de obligaciones', 'ADMINISTRADOR BLOQUEO OBLIGACIONES');
INSERT INTO role (id, description, name) VALUES (30, 'Reversador de obligaciones emitidas', 'ADMINISTRADOR BAJA OBLIGACIONES');
INSERT INTO role (id, description, name) VALUES (31, 'Anulador de obligaciones', 'ADMINISTRADOR ANULACION OBLIGACIONES');
INSERT INTO role (id, description, name) VALUES (32, 'Reimpresor de obligaciones', 'ADMINISTRADOR REIMPRESION OBLIGACIONES');
INSERT INTO role (id, description, name) VALUES (33, 'Administrador de preemisiones', 'ADMINISTRADOR PREEMISION OBLIGACIONES');
INSERT INTO role (id, description, name) VALUES (34, 'Permisos para realizar traspasos de dominio desde avalúos y catastos', 'TRASPASOS DE DOMINIO');
INSERT INTO role (id, description, name) VALUES (35, 'Permisos para crear convenios o facilidades de pago, ya sea para obligaciones vencidas o por vencer.', 'CONVENIO DE PAGO');
INSERT INTO role (id, description, name) VALUES (36, 'Permisos para Administración y Configuracion', 'INFORMATICA');
INSERT INTO role (id, description, name) VALUES (37, 'Permiso para visualizar el reporte de emision de una fecha determinada', 'REPORTE DE EMISION');
INSERT INTO role (id, description, name) VALUES (38, 'Permisos para la creaciòn de notas de crèdito', 'NOTAS DE CREDITO');
INSERT INTO role (id, description, name) VALUES (39, 'Permisos para administrar los servicios de agua potable, crear y modificar servicios y medidores del servicio, abonados nuevos', 'ADMINISTRACION SERVICIOS AGUA POTABLE');
INSERT INTO role (id, description, name) VALUES (40, 'Permisos para revisar ', 'REPORTES CONTABILIDAD');
INSERT INTO role (id, description, name) VALUES (41, 'Reimpresor de facturas originales', 'ADMINISTRADOR REIMPRESION ORIGINALES');
INSERT INTO role (id, description, name) VALUES (42, 'Permite al usuario modificar las lecturas anterior y actual, agregar nuevos medidores con la categoria correspondiente ', 'EDICION DE LECTURA');
INSERT INTO role (id, description, name) VALUES (43, 'Permisos para la creacion y edicion de cementerios, bloques y unidades.', 'ADMINISTRACION DE CEMENTERIOS');
INSERT INTO role (id, description, name) VALUES (44, 'Permisos para registrar defunciones generales y alquileres o renovaciones de espacios de cementerio', 'REGISTRO DE DEFUNCIONES');
INSERT INTO role (id, description, name) VALUES (45, 'Permisos para generar certificados de patentes perdidos', 'CERTIFICADO DE RENTAS SYSTEM');
INSERT INTO role (id, description, name) VALUES (46, 'Rol Especial para emitir Predio Urbano', 'EMISION URBANA');
INSERT INTO role (id, description, name) VALUES (47, 'Rol Especial para emitir Predio Rustico', 'EMISION RURAL');
INSERT INTO role (id, description, name) VALUES (48, 'Rol Especial para emitir Solares no Edificados', 'EMISION SOLARES NO EDIFICADOS');
INSERT INTO role (id, description, name) VALUES (49, 'Rol para entregar Certificados de solvencia para traspasos de bienes inmuebles', 'CERTIFICADOS DE PROPIEDAD');
INSERT INTO role (id, description, name) VALUES (50, 'Permite cambiar el propietario de un dominio y sus obligaciones urbano/rustico y solares pendientes de pago', 'CAMBIAR PROPIETARIO Y OBLIGACIONES');
INSERT INTO role (id, description, name) VALUES (51, 'Para ver reporte de emision recaudación en modulo de Finanzas', 'REPORTE EMIS-REC FINANZAS');
INSERT INTO role (id, description, name) VALUES (52, 'Administrador de parqueadero', 'ADMINISTRADOR DE PARQUEADERO');
INSERT INTO role (id, description, name) VALUES (53, 'Administrador de mercados', 'ADMINISTRADOR DE MERCADOS');
INSERT INTO role (id, description, name) VALUES (54, 'Administrador de Regulación y Control', 'ADMINISTRADOR DE REGULACION Y CONTROL');
