#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.tax

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.cadaster.model.Property;
import ec.gob.gim.cadaster.model.Domain;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.adjunct.PropertyAppraisal;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;


#declare any global variables here
rule "Contribución Cuerpo de Bomberos"
	no-loop true
	salience 0
	when
		$itemBomberos : Item(entry.code == "00472");
		$mb : MunicipalBond();
		$appraisal : PropertyAppraisal();
	then
		Item itemBase = $mb.getItems().get(0);
		System.out.println("RULE VALOR BASE BOMBEROS ---> "+itemBase.getValue());
		$itemBomberos.setValue(new BigDecimal(0.00015).multiply(itemBase.getValue()));		
		$itemBomberos.setTotal($itemBomberos.getValue());
end


