#impuesto predial urbano 2016
package gim.src.rules.ec.gob.gim.pf2011.tax

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.cadaster.model.Property;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.common.model.LegalEntity;
import ec.gob.gim.common.model.Resident;
import ec.gob.gim.common.model.LegalEntityType;
import ec.gob.gim.revenue.model.adjunct.PropertyAppraisal;
import java.util.Date;
import java.math.BigDecimal;


function calculationPropertyTaxes(Item $itemBase, PropertyAppraisal $appraisal, MunicipalBond $mb){
    
    Date serviceDate = $mb.getServiceDate();

    #"Impuesto predial urbano institucion municipal"
    if(($mb.getResident() != null) && 
            ($mb.getResident().getClass() == LegalEntity.class)
         && (((LegalEntity)$mb.getResident()).getLegalEntityType().name() == "MUNICIPAL")){

        $itemBase.setTotal(BigDecimal.ZERO);    
        $mb.setExpirationDate(new Date(serviceDate.getYear(), 11, 31));

    }else 
        if(($mb.getResident() != null) && 
        ($mb.getResident().getClass() == LegalEntity.class) && 
        (((LegalEntity)$mb.getResident()).getLegalEntityType().name() == "FIREFIGHTERS")){

        #"Impuesto predial urbano institucion bomberos"
        $itemBase.setTotal(BigDecimal.ZERO);    
        $mb.setExpirationDate(new Date(serviceDate.getYear(), 11, 31));

    }else 
        if(($mb.getResident() != null) && 
        ($mb.getResident().getClass() == LegalEntity.class) &&
        (((LegalEntity)$mb.getResident()).getLegalEntityType().name() == "PUBLIC")){

        #"Impuesto predial urbano institucion publica"
        $itemBase.setTotal(BigDecimal.ZERO);    
        $mb.setExpirationDate(new Date(serviceDate.getYear(), 11, 31));

    }else
        if(($mb.getResident() != null) && ($mb.getResident().getClass() == LegalEntity.class) && (((LegalEntity)$mb.getResident()).getLegalEntityType().name() == "PRIVATE")){

        #"Impuesto predial urbano institucion privada"
        $itemBase.setTotal(new BigDecimal(0.00055).multiply($itemBase.getValue().subtract($appraisal.getExemptionValue())));
        $mb.setExpirationDate(new Date(serviceDate.getYear(), 11, 31));
    
    }else if(($mb.getResident() != null) && 
        ($mb.getResident().getClass() == LegalEntity.class) && 
        (((LegalEntity)$mb.getResident()).getLegalEntityType().name() == "WELFARE")){

        #"Impuesto predial urbano institucion sin fines de lucro"
        $itemBase.setTotal(BigDecimal.ZERO);    
        $mb.setExpirationDate(new Date(serviceDate.getYear(), 11, 31));
    
    }else{
        $itemBase.setTotal(new BigDecimal(0.00055).multiply($itemBase.getValue().subtract($appraisal.getExemptionValue())));
        $mb.setExpirationDate(new Date(serviceDate.getYear(), 11, 31));
    }
}
 

rule "Impuesto predial urbano-ALL"
    no-loop true
    salience 210
    when
        $itemBase : Item(entry.code == "00056");
        $mb : MunicipalBond();
        $appraisal : PropertyAppraisal();               
    then    
        calculationPropertyTaxes($itemBase, $appraisal, $mb);
end