#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.tax

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.cadaster.model.Property;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.common.model.LegalEntity;
import ec.gob.gim.common.model.Resident;
import ec.gob.gim.common.model.LegalEntityType;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.revenue.model.adjunct.PropertyAppraisal;
import java.util.Date;
import java.math.BigDecimal;


rule "Impuesto predial rustico institucion publica"
	no-loop true
	salience 10
	when
		$itemBase : Item(entry.code == "00057");
		$mb : MunicipalBond();
		$appraisal : PropertyAppraisal();
		eval(($mb.getResident() != null) && ($mb.getResident().getClass() == LegalEntity.class) && (((LegalEntity)$mb.getResident()).getLegalEntityType().name() == "PUBLIC"))
	then
		$itemBase.setTotal(BigDecimal.ZERO);
end

#declare any global variables here
rule "Impuesto predial rustico"
	no-loop true
	salience 20
	when
		$itemBase : Item(entry.code == "00057");
		$mb : MunicipalBond();
		$appraisal : PropertyAppraisal();
	then
	    Date serviceDate = $mb.getServiceDate();
		$itemBase.setTotal(new BigDecimal(0.001).multiply($itemBase.getValue().subtract($appraisal.getExemptionValue())));
		$mb.setExpirationDate(new Date(serviceDate.getYear(), 11, 31));
end


