#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.tax

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.rental.model.Space;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.rental.model.SpaceType;
import java.math.BigDecimal;
import java.math.RoundingMode;


#declare any global variables here
rule "Alquilar espacio publicitario para valla con area menor o igual a 9 m2"
	no-loop true
	salience 50
	when
		$itemBase : Item(entry.code == "00120");
		$mb : MunicipalBond();	
		$space : Space(totalArea <= 9);		
	then 
		$itemBase.setValue(new BigDecimal($space.getCurrentContract().getTotalMonths() * 400).divide(new BigDecimal(12),4,RoundingMode.HALF_EVEN));		
		$mb.setDescription("ALQUILER DE ESPACIO PUBLICO PARA PUBLICIDAD");
		$itemBase.setTotal($itemBase.getValue());
end

rule "Alquilar espacio publicitario para valla con area mayor a 9 m2"
	no-loop true
	salience 50
	when
		$itemBase : Item(entry.code == "00120");
		$mb : MunicipalBond();
		$space : Space(totalArea > 9);	
	then 
		$itemBase.setValue(new BigDecimal($space.getCurrentContract().getTotalMonths()).multiply(new BigDecimal(400).divide(new BigDecimal(12),4,RoundingMode.HALF_EVEN)));			
		$itemBase.setValue($itemBase.getValue().add(new BigDecimal($space.getCurrentContract().getTotalMonths()).multiply(new BigDecimal(50)).multiply(new BigDecimal($space.getTotalArea() - 9)).divide(new BigDecimal(12),4,RoundingMode.HALF_EVEN)));
		$mb.setDescription("ALQUILER DE ESPACIO PUBLICO PARA PUBLICIDAD");
		$itemBase.setTotal($itemBase.getValue());
end

