#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.tax

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.rental.model.Space;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.rental.model.SpaceType;
import java.math.BigDecimal;
import java.math.RoundingMode;


rule "Alquilar espacio para paleta"
	no-loop true
	salience 50
	when
		$itemBase : Item(entry.code == "00418");
		$mb : MunicipalBond();
		$space : Space(spaceType.name == "PALETA");		
	then 
		$itemBase.setValue(new BigDecimal($space.getCurrentContract().getTotalMonths() * 400).divide(new BigDecimal(12),4,RoundingMode.HALF_EVEN));	
		$mb.setDescription("ALQUILER DE ESPACIO PUBLICO PARA PALETA");
		$itemBase.setTotal($itemBase.getValue());
		#calculateTotal();
end

rule "Alquilar espacio para rotulo"
	no-loop true
	salience 50
	when
		$itemBase : Item(entry.code == "00418");
		$mb : MunicipalBond();
		$space : Space(spaceType.name == "ROTULO");	
	then 
		$itemBase.setValue(new BigDecimal($space.getCurrentContract().getTotalMonths() * 20).divide(new BigDecimal(12),4,RoundingMode.HALF_EVEN).multiply(new BigDecimal($space.getTotalArea())));	
		$mb.setDescription("ALQUILER DE ESPACIO PUBLICO PARA ROTULO");
		$itemBase.setTotal($itemBase.getValue());
		#calculateTotal();
end



