#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.tax

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import org.gob.gim.revenue.view.EntryValueItem;
import ec.gob.gim.common.model.Person;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;


#declare any global variables here
rule "Revalidacion del Permiso de Construccion"
	no-loop true
	salience 50
	when		
		$itemBase : Item(entry.code == "00069");	
		$mb : MunicipalBond();	
		eval($mb.getExempt()==false && $mb.getIsNoPasiveSubject()==false);
	then 		
		$mb.setDescription("Revalidacion del Permiso de Construccion");		
		$itemBase.setTotal($itemBase.getValue().multiply(new BigDecimal(0.0005)).add(new BigDecimal(0.80)));			
end