package ec.gob.gim.rules.pf2011
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.common.model.FiscalPeriod;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;


function BigDecimal calculateSurcharge(java.util.Date serviceDate){
        java.util.Date actual = java.util.Calendar.getInstance().getTime();
                
        if(serviceDate.getYear() != actual.getYear() ){
                return new java.math.BigDecimal(0.1);
        }
        
        #Desde el 01 de Julio
        java.util.Date firstRange = new java.util.Date(actual.getYear(),6,1);
        if(actual.after(firstRange) || actual.equals(firstRange)){
                return new java.math.BigDecimal(0.1);
        }
        
        return new BigDecimal(0);
                
}


#list any import classes here.

rule "Recargo Impuesto predial"
        no-loop true
        salience 0
        when            
                $itemPredio : Item(entry.name == "RECARGO IMPUESTO PREDIAL");         
                $mb : MunicipalBond();  
        then            
                $mb.calculateValue();                           
                $itemPredio.setTotal($mb.getItems().get(0).getTotal().multiply(calculateSurcharge($mb.getServiceDate())));              
end