ALTER TABLE account DISABLE TRIGGER ALL;

INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (1,'0','NO PATRIMONIAL',NULL,NULL,'A.POST. 0',NULL,false,'A.ANT. 0',NULL,false,NULL);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (2,'1','ACTIVO',NULL,NULL,'A.POST. 1',NULL,false,'A.ANT. 1',NULL,false,1);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (3,'1.1','OPERACIONAL',NULL,NULL,'A.POST. 1.1',NULL,false,'A.ANT. 1.1',NULL,false,2);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (4,'1.1.3','CUENTAS POR COBRAR ANTICIPOS DE FONDOS DE AÑOS ANTERIORES','3.8.01.02.01','38010201','A.POST. 1.1.3','A.POST. 3.8.01.02.01',false,'A.ANT. 1.1.3','A.ANT. 3.8.01.02.01',false,3);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (5,'1.1.3.11','IMPUESTOS',NULL,NULL,'A.POST. 1.1.3.11',NULL,true,'A.ANT. 1.1.3.11',NULL,false,4);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (6,'1.1.3.11.01','A LOS PREDIOS URBANOS','1.1.02.01.01',NULL,'A.POST. 1.1.3.11.01',NULL,false,'A.ANT. 1.1.3.11.01',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (7,'1.1.3.11.02','A LOS PREDIOS RUSTICOS','1.1.02.02.01',NULL,'A.POST. 1.1.3.11.02',NULL,false,'A.ANT. 1.1.3.11.02',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (8,'1.1.3.11.03','DE ALCABALAS','1.1.02.06',NULL,'A.POST. 1.1.3.11.03',NULL,false,'A.ANT. 1.1.3.11.03',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (9,'1.1.3.11.04','A LOS ACTIVOS TOTALES','1.1.02.07',NULL,'A.POST. 1.1.3.11.04',NULL,false,'A.ANT. 1.1.3.11.04',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (10,'1.1.3.11.05','OTROS IMPUESTOS SOBRE LA PROPIEDAD',NULL,NULL,'A.POST. 1.1.3.11.05',NULL,false,'A.ANT. 1.1.3.11.05',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (11,'1.1.3.11.06','A LOS ESPECTACULOS PUBLICOS','1.1.03.12',NULL,'A.POST. 1.1.3.11.06',NULL,false,'A.ANT. 1.1.3.11.06',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (12,'1.1.3.11.07','PATENTES COMERCIALES, INDUSTRIALES Y DE SERVICIO','1.1.07.04',NULL,'A.POST. 1.1.3.11.07',NULL,false,'A.ANT. 1.1.3.11.07',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (13,'1.1.3.11.08','OTROS IMPUESTOS','1.1.07.99',NULL,'A.POST. 1.1.3.11.08',NULL,false,'A.ANT. 1.1.3.11.08',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (14,'1.1.3.11.09','AL DESPOSTE DE GANADO',NULL,NULL,'A.POST. 1.1.3.11.09',NULL,false,'A.ANT. 1.1.3.11.09',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (15,'1.1.3.11.10','AL VALOR AGREGADO',NULL,NULL,'A.POST. 1.1.3.11.10',NULL,false,'A.ANT. 1.1.3.11.10',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (16,'1.1.3.11.11','A LA INSCRIPCION EN EL REGISTRO DE LA PROPIEDAD O EN EL REGISTRO MERCANTIL',NULL,NULL,'A.POST. 1.1.3.11.11',NULL,false,'A.ANT. 1.1.3.11.11',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (17,'1.1.3.11.12','COPIA DE DOCUMENTOS Y CERTIFICADOS','1.1.02.01.04',NULL,'A.POST. 1.1.3.11.12',NULL,false,'A.ANT. 1.1.3.11.12',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (18,'1.1.3.11.13','TASA DE SERVICIO ADMINISTRATIVO','1.1.02.01.02',NULL,'A.POST. 1.1.3.11.13',NULL,false,'A.ANT. 1.1.3.11.13',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (19,'1.1.3.11.14','SOLAR NO EDIFICADO','1.1.02.01.03',NULL,'A.POST. 1.1.3.11.14',NULL,false,'A.ANT. 1.1.3.11.14',NULL,false,5);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (20,'1.1.3.11.15','TASA DE SERVICIO DE COMPUTO','1.1.02.02.02',NULL,'A.POST. 1.1.3.11.15',NULL,false,'A.ANT. 1.1.3.11.15',NULL,false,5);


INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (21,'1.1.3.13','TASAS Y CONTRIBUCIONES',NULL,NULL,'A.POST. 1.1.3.13',NULL,false,'A.ANT. 1.1.3.13',NULL,false,4);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (22,'1.1.3.13.01','ACCESOS A LUGARES PUBLICOS',NULL,NULL,'A.POST. 1.1.3.13.01',NULL,true,'A.ANT. 1.1.3.13.01',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (23,'1.1.3.13.02','OCUPACION DE LUGARES PUBLICOS','1.3.01.03',NULL,'A.POST. 1.1.3.13.02',NULL,true,'A.ANT. 1.1.3.13.02',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (24,'1.1.3.13.03','ESPECIES FISCALES','1.3.01.06',NULL,'A.POST. 1.1.3.13.03',NULL,true,'A.ANT. 1.1.3.13.03',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (25,'1.1.3.13.04','VENTA DE BASES',NULL,NULL,'A.POST. 1.1.3.13.04',NULL,true,'A.ANT. 1.1.3.13.04',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (26,'1.1.3.13.05','PRESTACION DE SERVICIOS (CENTRO DE COMPUTO)',NULL,NULL,'A.POST. 1.1.3.13.05',NULL,true,'A.ANT. 1.1.3.13.05',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (27,'1.1.3.13.06','RODAJE DE VEHICULOS MOTORIZADOS','1.3.01.09',NULL,'A.POST. 1.1.3.13.06',NULL,true,'A.ANT. 1.1.3.13.06',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (28,'1.1.3.13.07','INSCRIPCIONES, REGISTROS Y MATRICULAS',NULL,NULL,'A.POST. 1.1.3.13.07',NULL,true,'A.ANT. 1.1.3.13.07',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (29,'1.1.3.13.08','PERMISOS, LICENCIAS Y PATENTES','1.3.01.12',NULL,'A.POST. 1.1.3.13.08',NULL,true,'A.ANT. 1.1.3.13.08',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (30,'1.1.3.13.09','SERVICIOS DE CAMALES','1.3.01.14',NULL,'A.POST. 1.1.3.13.09',NULL,true,'A.ANT. 1.1.3.13.09',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (31,'1.1.3.13.10','FISCALIZACION DE OBRAS',NULL,NULL,'A.POST. 1.1.3.13.10',NULL,true,'A.ANT. 1.1.3.13.10',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (32,'1.1.3.13.11','RECOLECCION DE BASURA','1.3.01.16',NULL,'A.POST. 1.1.3.13.11',NULL,true,'A.ANT. 1.1.3.13.11',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (33,'1.1.3.13.12','OTRAS TASAS (SERVICIOS AMBIENTALES)','1.3.01.99.01',NULL,'A.POST. 1.1.3.13.12',NULL,true,'A.ANT. 1.1.3.13.12',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (34,'1.1.3.13.13','PAVIMENTACION DE CALLES','1.3.04.06.01',NULL,'A.POST. 1.1.3.13.13',NULL,true,'A.ANT. 1.1.3.13.13',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (35,'1.1.3.13.14','ADOQUINADO DE CALLLES','1.3.04.06.02',NULL,'A.POST. 1.1.3.13.14',NULL,true,'A.ANT. 1.1.3.13.14',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (36,'1.1.3.13.15','MEJORES EN OBRAS DE ALCANTARILLADO','1.3.04.09.01',NULL,'A.POST. 1.1.3.13.15',NULL,true,'A.ANT. 1.1.3.13.15',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (37,'1.1.3.13.16','APROBACION DE PLANOS E INSPECCION DE CONSTRUCCIONES','1.3.01.18.01',NULL,'A.POST. 1.1.3.13.16',NULL,true,'A.ANT. 1.1.3.13.16',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (38,'1.1.3.13.17','CONEXION Y RECONEXION DE SERVICIO DE ALCANTARILLADO Y CANALIZACION','1.3.01.20.01',NULL,'A.POST. 1.1.3.13.17',NULL,true,'A.ANT. 1.1.3.13.17',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (39,'1.1.3.13.18','CONEXION Y RECONEXION DEL SERVICIO DE AGUA POTABLE','1.3.01.21.01',NULL,'A.POST. 1.1.3.13.18',NULL,true,'A.ANT. 1.1.3.13.18',NULL,false,21);

INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (40,'1.1.3.13.20','APROBACION DE LINEAS DE FABRICA','1.3.01.18.02',NULL,'A.POST. 1.1.3.13.20',NULL,true,'A.ANT. 1.1.3.13.20',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (41,'1.1.3.13.21','INSPECCION DE CONSTRUCCIONES',NULL,NULL,'A.POST. 1.1.3.13.21',NULL,true,'A.ANT. 1.1.3.13.21',NULL,false,21);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (42,'1.1.3.13.99','OTRAS TASAS','1.3.01.99.02',NULL,'A.POST. 1.1.3.13.99',NULL,true,'A.ANT. 1.1.3.13.99',NULL,false,21);


INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (43,'1.1.3.14','VENTA DE BIENES Y SERVICIOS',NULL,NULL,'A.POST. 1.1.3.14',NULL,false,'A.ANT. 1.1.3.14',NULL,false,4);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (44,'1.1.3.14.01','AGROPECUARIOS Y FORESTALES',NULL,NULL,'A.POST. 1.1.3.14.01',NULL,true,'A.ANT. 1.1.3.14.01',NULL,false,43);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (45,'1.1.3.14.02','VENTA DE ABONOS ORGANICOS',NULL,NULL,'A.POST. 1.1.3.14.02',NULL,true,'A.ANT. 1.1.3.14.02',NULL,false,43);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (46,'1.1.3.14.03','MATERIALES Y ACCESORIOS DE AGUA POTABLE',NULL,NULL,'A.POST. 1.1.3.14.03',NULL,true,'A.ANT. 1.1.3.14.03',NULL,false,43);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (47,'1.1.3.14.04','VENTA DE MEDIDORES','1.4.02.06.02',NULL,'A.POST. 1.1.3.14.04',NULL,true,'A.ANT. 1.1.3.14.04',NULL,false,43);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (48,'1.1.3.14.05','VENTA DE PRODUCTOS Y MATERIALES, TACHOS DE BASURA','1.4.02.99.01',NULL,'A.POST. 1.1.3.14.05',NULL,true,'A.ANT. 1.1.3.14.05',NULL,false,43);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (49,'1.1.3.14.06','FACTURACION CONSUMO DE AGUA POTABLE','1.4.03.01.01',NULL,'A.POST. 1.1.3.14.06',NULL,true,'A.ANT. 1.1.3.14.06',NULL,false,43);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (50,'1.1.3.14.07','FACTURACION SERVICIO ALCANTARILLADO','1.4.03.03.01',NULL,'A.POST. 1.1.3.14.07',NULL,true,'A.ANT. 1.1.3.14.07',NULL,false,43);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (51,'1.1.3.14.08','SERVICIOS DE CEMENTERIO','1.7.02.01',NULL,'A.POST. 1.1.3.14.08',NULL,true,'A.ANT. 1.1.3.14.08',NULL,false,43);

INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (52,'1.1.3.17','RENTA DE INVERSIONES Y MULTAS',NULL,NULL,'A.POST. 1.1.3.17',NULL,false,'A.ANT. 1.1.3.17',NULL,false,4);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (55,'1.1.3.17.03','ARRENDAMIENTO DE LOCALES EN EL MERCADO','1.7.02.02.02',NULL,'A.POST. 1.1.3.17.03',NULL,false,'A.ANT. 1.1.3.17.03',NULL,false,52);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (64,'1.1.3.17.12','INTERESES POR MORA EN OBLIGACIONES TRIBUTARIAS','1.7.03.01.01',NULL,'A.POST. 1.1.3.17.12',NULL,false,'A.ANT. 1.1.3.17.12',NULL,false,52);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (69,'1.1.3.17.17','ARRENDAMIENTO DE MAQUINARIAS Y EQUIPO','1.7.02.04.01',NULL,'A.POST. 1.1.3.17.17',NULL,false,'A.ANT. 1.1.3.17.17',NULL,false,52);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (75,'1.1.3.19.05','ABONOS','1.9.04.99.99',NULL,'A.POST. 1.1.3.19.05',NULL,false,'A.ANT. 1.1.3.19.05',NULL,false,52);

INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (70,'1.1.3.19','OTROS INGRESOS',NULL,NULL,'A.POST. 1.1.3.19',NULL,false,'A.ANT. 1.1.3.19',NULL,false,4);
INSERT INTO account (id, accountcode, accountname, budgetcertificatecode,budgetcertificatename, futureyearsaccountcode, futureyearsbudgetcertificatecode, isshowsummary, previousyearsaccountcode, previousyearsbudgetcertificatecode, showsubtotal,parent_id) VALUES (74,'1.1.3.19.04','OTROS NO ESPECIFICADOS','1.9.04.99.01',NULL,'A.POST. 1.1.3.19.04',NULL,false,'A.ANT. 1.1.3.19.04',NULL,false,70);


ALTER TABLE account ENABLE TRIGGER ALL;
