#created on: Oct 31, 2011
package ec.gob.gim.rules.pf2011
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;
import ec.gob.gim.waterservice.model.MaintenanceEntryDTO;



rule "Recargo Mantenimiento Agua Potable"
	no-loop true
	salience 0
	when		
		$item : Item(entry.code == "00544");		
		$mb : MunicipalBond();
		$med : MaintenanceEntryDTO(value > 0);		
	then				
		$item.setTotal($med.getValue());		
		$item.setValue($med.getValue());		
end
