#created on: Oct 31, 2011
package ec.gob.gim.rules.pf2011
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.common.model.FiscalPeriod;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;


function BigDecimal calculateSurcharge(java.util.Date expirationDate){
	java.util.Date actual = java.util.Calendar.getInstance().getTime();
		
	if(expirationDate.getYear() != actual.getYear() ){
	    BigDecimal diference = new BigDecimal(actual.getYear() - expirationDate.getYear() + 1);
		return new java.math.BigDecimal(0.1).multiply(diference);
	}
	
	//Desde el 01 de Julio
	//java.util.Date firstRange = new java.util.Date(actual.getYear(),6,1);
	if(actual.getMonth() >= 6){
		return new java.math.BigDecimal(0.1);
	}
	
	return new BigDecimal(0);
}


#list any import classes here.

rule "Recargo Impuesto predial rustico"
	no-loop true
	salience 0
	when		
		$itemPredio : Item(entry.name == "RECARGO IMPUESTO PREDIAL RUSTICO");		
		$mb : MunicipalBond();	
	then		
		//$mb.calculateValue();
		$itemPredio.setTotal($mb.getItems().get(0).getTotal().multiply(calculateSurcharge($mb.getExpirationDate())));		
end
