#created on: Oct 31, 2011
package ec.gob.gim.rules.pf2011
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.common.model.FiscalPeriod;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;
import org.gob.gim.common.DateUtils;
import java.util.Calendar;
import java.util.Date;

function BigDecimal findSurchargeFactor(Date expiration){
	Calendar paymentDate = DateUtils.getTruncatedInstance(new Date());
	Calendar expirationDate = DateUtils.getTruncatedInstance(expiration);
	
	if(paymentDate.after(expirationDate)){
		Integer months = (paymentDate.get(Calendar.YEAR) - expirationDate.get(Calendar.YEAR)) * 12 +
			 		     (paymentDate.get(Calendar.MONTH)- expirationDate.get(Calendar.MONTH));
		System.out.println("MONTHS DIFF -----> " + months);
	
		if( months <= 12){
			return new java.math.BigDecimal(0.01).multiply(new BigDecimal(months));
		} else {
			return new java.math.BigDecimal(0.15).multiply(new BigDecimal(months));
		}
	}
	return new BigDecimal(0);
}


rule "Recargo de contribucion especial de mejoras"
	no-loop true
	salience 0
	when		
		$itemPredio : Item(entry.name == "RECARGO CONTRIBUCION ESPECIAL MEJORAS");
		$mb : MunicipalBond();
	then		
		$itemPredio.setTotal($mb.getItems().get(0).getTotal().multiply(findSurchargeFactor($mb.getExpirationDate())));		
end
