#created on: 2014-jul-03
package ec.gob.gim.rules.pf2011
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.common.model.FiscalPeriod;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;
import org.gob.gim.common.DateUtils;
import java.util.Calendar;
import java.util.Date;

function BigDecimal findSurchargeFactor(Date expiration){
	Calendar paymentDate = DateUtils.getTruncatedInstance(new Date());
	Calendar expirationDate = DateUtils.getTruncatedInstance(expiration);
	
	if(paymentDate.after(expirationDate)){
		if (paymentDate.get(Calendar.YEAR) == expirationDate.get(Calendar.YEAR)){
			Integer days = paymentDate.get(Calendar.DAY_OF_YEAR) - expirationDate.get(Calendar.DAY_OF_YEAR);
			System.out.println("DAYS DIFFERENCE -----> " + days);
		
			if( days >= 10){
				return new java.math.BigDecimal(1);
			} else {
				return new java.math.BigDecimal(0.1).multiply(new BigDecimal(days));
			}
		} else
			return new java.math.BigDecimal(1);
	}
	return new BigDecimal(0);
}


rule "Recargo multas SIMERT"
	no-loop true
	salience 0
	when		
		$itemPredio : Item(entry.id == 586);
		$mb : MunicipalBond();
	then		
		$itemPredio.setTotal($mb.getItems().get(0).getTotal().multiply(findSurchargeFactor($mb.getExpirationDate())));		
end
