#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.market

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.market.model.Stand;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.market.model.StandType;
import java.math.BigDecimal;

dialect "java"

rule "Alguiler ENERGIA ELECTRICA valor fijo"
    no-loop true
    salience 1
    when
        $itemBase : Item(entry.code == "00236");
        $mb : MunicipalBond();
        $stand : Stand(standType.name == "ENERGIA ELECTRICA");
        #eval($stand.getIsCalculated()==false);
    then
        $itemBase.setValue($stand.getValue());
        $itemBase.setTotal($itemBase.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));
        System.out.println("...................................ENERGIA ELECTRICA valor fijo: " + $itemBase.getTotal());
end

##########################################

rule "Alguiler ENERGIA ELECTRICA valor fijo ventanilla"
    no-loop true
    salience 4
    when
        $itemBase : Item(entry.code == "00236");
        $mb : MunicipalBond();
    then
        #$itemBase.setValue($mb.getValue());
        $itemBase.setTotal($itemBase.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));
        System.out.println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx ENERGIA ELECTRICA valor fijo ventanilla : xxxxxxxxxxxxx " + $itemBase.getTotal());
end