#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.market

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.market.model.Stand;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.market.model.StandType;
import java.math.BigDecimal;

dialect "java"

rule "Alguiler VIA PUBLICA valor fijo"
    no-loop true
    salience 2
    when
        $itemBase : Item(entry.code == "00034");
        $mb : MunicipalBond();
        $stand : Stand(standType.name == "VIA PUBLICA");
        #eval($stand.getIsCalculated()==false);
    then
        $itemBase.setValue($stand.getValue());
        $itemBase.setTotal($itemBase.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));
        System.out.println("...................................VIA PUBLICA: " + $itemBase.getTotal());
end

##########################################

rule "Alguiler VIA PUBLICA valor fijo ventanilla"
        no-loop true
        salience 4
        when
                $itemBase : Item(entry.code == "00034");
                $mb : MunicipalBond();
        then
                #$itemBase.setValue($mb.getValue());
                $itemBase.setTotal($itemBase.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));
                System.out.println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx VIA PUBLICA valor fijo ventanilla : xxxxxxxxxxxxx " + $itemBase.getTotal());
end