#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.market

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.revenue.model.MunicipalBond;
import java.math.BigDecimal;
import java.util.Date;
import ec.gob.gim.consession.model.ConcessionItem;
import ec.gob.gim.consession.model.ConcessionPlaceType;
import ec.gob.gim.consession.model.ConcessionPlace;

import ec.gob.gim.commercial.model.TouristLicenseItem;

dialect "java"

function Date calculateExpirationDate(Date a, MunicipalBond m){
        if(m.getIsExpirationDateDefined()) return m.getExpirationDate();        
        return new Date(a.getYear(),4,31);      
}

rule "LICEN. UNIC. ANUAL DE FUNC. TURISMO valor fijo"
        no-loop true
        salience 2
        when
                $itemBase : Item(entry.code == "00123");
                $mb : MunicipalBond();
                $tli : TouristLicenseItem();
                #$cItem : ConcessionItem(place.consessionPlaceType.name == "EST. PERMANENTE SIMERT");
                #eval($stand.getIsCalculated()==false);
        then
        		$mb.setExpirationDate(calculateExpirationDate($mb.getServiceDate(), $mb));
                $itemBase.setValue($tli.getValue());
                $itemBase.setTotal($itemBase.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));
                System.out.println("...................................LICEN. UNIC. ANUAL DE FUNC. TURISMO: " + $itemBase.getTotal());
end

##########################################

rule "LICEN. UNIC. ANUAL DE FUNC. TURISMO valor fijo ventanilla"
        no-loop true
        salience 4
        when
                $itemBase : Item(entry.code == "00123");
                $mb : MunicipalBond();
        then
                #$itemBase.setValue($mb.getValue());
                $mb.setExpirationDate(calculateExpirationDate($mb.getServiceDate(), $mb));
                $itemBase.setTotal($itemBase.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));
                System.out.println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx LICEN. UNIC. ANUAL DE FUNC. TURISMO valor fijo ventanilla : xxxxxxxxxxxxx " + $itemBase.getTotal());
end
