package gim.src.rules.ec.gob.gim.pf2011.tax

import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.common.model.Person;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.revenue.model.adjunct.MiningConcession;
import java.math.BigDecimal;

rule "Concesión Exploración"
	no-loop true
	salience 10
	when
		$itemBase : Item(entry.code == "RPM-ICM");
		$mb : MunicipalBond(items contains $itemBase);
		$concession : MiningConcession(concessionType.name == "EXPLORATION");
		
	then
		$itemBase.setValue(new BigDecimal(30)); 
		$itemBase.setTotal($itemBase.getValue().multiply($itemBase.getAmount()));
end

rule "Concesión Explotación"
	no-loop true
	salience 10
	when
		$itemBase : Item(entry.code == "RPM-ICM");
		$mb : MunicipalBond(items contains $itemBase);
		$concession : MiningConcession(concessionType.name == "EXPLOITATION");
		
	then 
		$itemBase.setValue(new BigDecimal(100)); 
		$itemBase.setTotal($itemBase.getValue().multiply($itemBase.getAmount()));	
end

rule "Autorización Explotación"
	no-loop true
	salience 10
	when
		$itemBase : Item(entry.code == "RPM-ICM");
		$mb : MunicipalBond(items contains $itemBase);
		$concession : MiningConcession(concessionType.name == "AUTHORIZATION_EXPLOITATION");
		 
	then 
		$itemBase.setValue(new BigDecimal(100)); 
		$itemBase.setTotal($itemBase.getValue().multiply($itemBase.getAmount()));		
end