#created on: Nov 12, 2011
package gim.src.rules.ec.gob.gim.pf2011.tax

#list any import classes here.
import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.cadaster.model.Property;
import ec.gob.gim.cadaster.model.Domain;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.common.model.LegalEntity;
import ec.gob.gim.common.model.Resident;
import ec.gob.gim.common.model.LegalEntityType;
import ec.gob.gim.revenue.model.Item;
import ec.gob.gim.revenue.model.adjunct.PropertyAppraisal;
import java.math.BigDecimal;


rule "Impuesto predial rustico institucion publica"
	no-loop true
	salience 10
	when
		$itemBase : Item(entry.code == "IPR-PRA");
		$mb : MunicipalBond();
		$appraisal : PropertyAppraisal();
		eval(($mb.getResident() != null) && ($mb.getResident().getClass() == LegalEntity.class) && (((LegalEntity)$mb.getResident()).getLegalEntityType().name() == "PUBLIC"))
	then
		$itemBase.setTotal(BigDecimal.ZERO);
		$mb.setGroupingCode($mb.getReference());
end

rule "Impuesto predial rustico"
	no-loop true
	salience 20
	when
		$itemBase : Item(entry.code == "IPR-PRA");
		$mb : MunicipalBond();
		//$appraisal : PropertyAppraisal();
	then
		//$itemBase.setTotal(new BigDecimal(0.00078).multiply($itemBase.getValue().subtract($appraisal.getExemptionValue())));
		$itemBase.setTotal(new BigDecimal(0.00078).multiply($itemBase.getValue()));
		$mb.setGroupingCode($mb.getReference());
end


