#created on: Oct 31, 2011
package ec.gob.gim.rules.pf2011
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
#list any import classes here.



#declare any global variables here

rule "Iva 12%"
	no-loop true
	when
		$itemIva : Item(entry.name == "IVA");
		$mb : MunicipalBond(items contains $itemIva);
		
	then
		System.out.println("Ejecutando regla del Iva");
		#Item itemBase = (Item)$mb.getItems().get(0);
			#$mb.setSubTotalCalculationIva(itemBase.getTotal());
		$mb.calculateTaxesTotal();
		$itemIva.setAmount($mb.getTaxesTotal());
		$itemIva.setValue(new java.math.BigDecimal(0.12));
		$itemIva.setTotal($itemIva.getValue());
end 
