package gim.src.rules.ec.gob.gim.pf2011.tax

import ec.gob.gim.revenue.model.Entry;
import ec.gob.gim.common.model.Person;
import ec.gob.gim.revenue.model.MunicipalBond;
import ec.gob.gim.revenue.model.Item;
import java.math.BigDecimal;

rule "Actos y contratos del Registro de la Propiedad"
	no-loop true
	salience 5
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval(($mb.getExempt() || $mb.getIsNoPasiveSubject())) 
	then 
		$itemBase.setTotal(new BigDecimal(0.0));
end

rule "Actos y contratos del Registro de la Propiedad 0.01 - 1.60"
	no-loop true
	salience 10
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 0 && $itemBase.getValue().doubleValue() <= 1.60) 
	then 
		$itemBase.setTotal(new BigDecimal(1.40));
end

rule "Actos y contratos del Registro de la Propiedad 1.61 - 3.00"
	no-loop true
	salience 15
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 1.60 && $itemBase.getValue().doubleValue() <= 3.00) 
	then 
		$itemBase.setTotal(new BigDecimal(1.80));
end

rule "Actos y contratos del Registro de la Propiedad 3.01 - 4.00"
	no-loop true
	salience 20
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 3.00 && $itemBase.getValue().doubleValue() <= 4.00) 
	then 
		$itemBase.setTotal(new BigDecimal(2.25));
end

rule "Actos y contratos del Registro de la Propiedad 4.01 - 6.00"
	no-loop true
	salience 25
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 4.0 && $itemBase.getValue().doubleValue() <= 6.00) 
	then 
		$itemBase.setTotal(new BigDecimal(2.80));
end


rule "Actos y contratos del Registro de la Propiedad 6.01 - 10.00"
	no-loop true
	salience 30
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 6.0 && $itemBase.getValue().doubleValue() <= 10.00) 
	then 
		$itemBase.setTotal(new BigDecimal(3.75));
end

rule "Actos y contratos del Registro de la Propiedad 10.01 - 14.00"
	no-loop true
	salience 35
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 10.0 && $itemBase.getValue().doubleValue() <= 14.00) 
	then 
		$itemBase.setTotal(new BigDecimal(4.50));
end


rule "Actos y contratos del Registro de la Propiedad 14.01 - 20.00"
	no-loop true
	salience 40
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 14.0 && $itemBase.getValue().doubleValue() <= 20.00) 
	then 
		$itemBase.setTotal(new BigDecimal(5.25));
end

rule "Actos y contratos del Registro de la Propiedad 20.01 - 30.00"
	no-loop true
	salience 45
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 20.0 && $itemBase.getValue().doubleValue() <= 30.00) 
	then 
		$itemBase.setTotal(new BigDecimal(6.50));
end

rule "Actos y contratos del Registro de la Propiedad 30.01 - 40.00"
	no-loop true
	salience 50
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 30.0 && $itemBase.getValue().doubleValue() <= 40.00) 
	then 
		$itemBase.setTotal(new BigDecimal(8.20));
end

rule "Actos y contratos del Registro de la Propiedad 40.01 - 80.00"
	no-loop true
	salience 55
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 40.0 && $itemBase.getValue().doubleValue() <= 80.00) 
	then 
		$itemBase.setTotal(new BigDecimal(11.25));
end

rule "Actos y contratos del Registro de la Propiedad 80.01 - 120.00"
	no-loop true
	salience 60
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 80.0 && $itemBase.getValue().doubleValue() <= 120.00) 
	then 
		$itemBase.setTotal(new BigDecimal(12.50));
end

rule "Actos y contratos del Registro de la Propiedad 120.01 - 200.00"
	no-loop true
	salience 65
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 120.0 && $itemBase.getValue().doubleValue() <= 200.00) 
	then 
		$itemBase.setTotal(new BigDecimal(17.25));
end

rule "Actos y contratos del Registro de la Propiedad 200.01 - 280.00"
	no-loop true
	salience 70
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 200.0 && $itemBase.getValue().doubleValue() <= 280.00) 
	then 
		$itemBase.setTotal(new BigDecimal(22.30));
end

rule "Actos y contratos del Registro de la Propiedad 280.01 - 400.00"
	no-loop true
	salience 75
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 280.0 && $itemBase.getValue().doubleValue() <= 400.00) 
	then 
		$itemBase.setTotal(new BigDecimal(26.00));
end


rule "Actos y contratos del Registro de la Propiedad 400.01 - 600.00"
	no-loop true
	salience 80
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 400.0 && $itemBase.getValue().doubleValue() <= 600.00) 
	then 
		$itemBase.setTotal(new BigDecimal(33.70));
end

rule "Actos y contratos del Registro de la Propiedad 600.01 - 800.00"
	no-loop true
	salience 85
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 600.0 && $itemBase.getValue().doubleValue() <= 800.00) 
	then 
		$itemBase.setTotal(new BigDecimal(37.0));
end

rule "Actos y contratos del Registro de la Propiedad 800.01 - 1200.00"
	no-loop true
	salience 90
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 800.0 && $itemBase.getValue().doubleValue() <= 1200.00) 
	then 
		$itemBase.setTotal(new BigDecimal(44.25));
end


rule "Actos y contratos del Registro de la Propiedad 1200.01 - 1600.00"
	no-loop true
	salience 95
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 1200.0 && $itemBase.getValue().doubleValue() <= 1600.00) 
	then 
		$itemBase.setTotal(new BigDecimal(58.90));
end

rule "Actos y contratos del Registro de la Propiedad 1600.01 - 2000.00"
	no-loop true
	salience 100
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 1600.0 && $itemBase.getValue().doubleValue() <= 2000.00) 
	then 
		$itemBase.setTotal(new BigDecimal(74.55));
end

rule "Actos y contratos del Registro de la Propiedad 2000.01 - 2400.00"
	no-loop true
	salience 110
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 2000.0 && $itemBase.getValue().doubleValue() <= 2400.00) 
	then 
		$itemBase.setTotal(new BigDecimal(80.0));
end

rule "Actos y contratos del Registro de la Propiedad 2400.01 - 2800.00"
	no-loop true
	salience 120
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 2400.0 && $itemBase.getValue().doubleValue() <= 2800.00) 
	then 
		$itemBase.setTotal(new BigDecimal(85.00));
end

rule "Actos y contratos del Registro de la Propiedad 2800.01 - 3200.00"
	no-loop true
	salience 130
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 2800.0 && $itemBase.getValue().doubleValue() <= 3200.00) 
	then 
		$itemBase.setTotal(new BigDecimal(90.00));
end

rule "Actos y contratos del Registro de la Propiedad 3200.01 - 3600.00"
	no-loop true
	salience 140
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 3200.0 && $itemBase.getValue().doubleValue() <= 3600.00) 
	then 
		$itemBase.setTotal(new BigDecimal(95.00));
end

rule "Actos y contratos del Registro de la Propiedad 3600.01 - 10000.00"
	no-loop true
	salience 150
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 3600.00 && $itemBase.getValue().doubleValue() <= 10000.00) 
	then 
		$itemBase.setTotal(new BigDecimal(100.00));
end

rule "Actos y contratos del Registro de la Propiedad mayor a 10000"
	no-loop true
	salience 45
	when
		$itemBase : Item(entry.code == "IRI-RPC");
		$mb : MunicipalBond(items contains $itemBase);
		eval($itemBase.getValue().doubleValue() > 10000) 
	then 
		BigDecimal $recargo = new BigDecimal(0.005).multiply($itemBase.getValue().subtract(new BigDecimal(10000)));
		$itemBase.setTotal($recargo.add(new BigDecimal(100.0)));
		$mb.setDescription("Vehículo con valor mayor a 40000");
end